name = "r2-manager-worker"
main = "worker/index.ts"       
compatibility_date = "2024-04-03"
workers_dev = true

[[d1_databases]]
binding = "METADATA"
database_name = "r2-manager-metadata"
database_id = "1f6511ad-3c7e-43f6-beed-831357c2c442"    # ※もし実際のD1のID（UUID）が分かればここに上書きしてください。不明ならこのままでOKです。

[[r2_buckets]]
binding = "R2"
bucket_name = "r2-bucket"             # ※もし実際のR2バケット名が違う場合は、ご自身のバケット名に書き換えてください。

[[unsafe.bindings]]
name = "RATE_LIMITER_READ"
type = "ratelimit"
namespace_id = "1001"
simple = { limit = 600, period = 60 }

[[unsafe.bindings]]
name = "RATE_LIMITER_WRITE"
type = "ratelimit"
namespace_id = "1002"
simple = { limit = 200, period = 60 }

[[unsafe.bindings]]
name = "RATE_LIMITER_DELETE"
type = "ratelimit"
namespace_id = "1003"
simple = { limit = 60, period = 60 }

# 従来の、より確実な静的ファイル配信設定に切り替えます
[site]
bucket = "./dist"

[vars]
TEAM_DOMAIN = "floral-grass-47e6.cloudflareaccess.com" # 👈 Zero Trustの設定画面にあるドメイン
POLICY_AUD = "d3531832-c1f7-492f-6a8f-11557deb023b" # 👈 Zero TrustのApplication設定からコピーできる文字列
